"""empty message

Revision ID: 31606e1372ec
Revises: e68f70e97cb8
Create Date: 2020-12-28 21:41:24.288497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31606e1372ec'
down_revision = 'e68f70e97cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
