"""empty message

Revision ID: 977c34c15caf
Revises: 2f5c89ae5c2c
Create Date: 2020-12-27 17:46:17.553834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977c34c15caf'
down_revision = '2f5c89ae5c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###
