"""empty message

Revision ID: ee4e1c734130
Revises: 7306e9d31301
Create Date: 2020-12-27 17:41:27.044691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee4e1c734130'
down_revision = '7306e9d31301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
